version: '3.4'

networks:
  mqtt_network:
    driver: bridge

services:
    mqtt:
        # image: emqx/emqx:5.8.0
        image: emqx/emqx-enterprise
        container_name: emqx
        ports:
          - "1883:1883"
          - "8083:8083"
          - "8084:8084"
          - "8883:8883"
          - "18083:18083"
        networks:
          - mqtt_network
        restart: unless-stopped
        volumes:
          - ./emqx_init/emqx.conf://opt/emqx/etc/emqx.conf
        environment:
          - EMQX_DASHBOARD__DEFAULT_USERNAME=${EMQX_DEFAULT_USERNAME}
          - EMQX_DASHBOARD__DEFAULT_PASSWORD=${EMQX_DEFAULT_PASSWORD}
    risingwave:
      container_name: risingwave_mqtt
      image: risingwavelabs/risingwave:v1.10.2
      command: single_node
      ports:
        - "4566:4566"
        - "5691:5691"
      restart: unless-stopped
      networks:
          - mqtt_network
    postgres:
      image: postgres:13
      environment:
        POSTGRES_PASSWORD: "${PG_DB_PASSWORD}"
        POSTGRES_USER : "${PG_DB_USERNAME}"
        POSTGRES_DB : "${PG_DB_NAME}"
      ports:
        - "${PG_DB_PORT}:5432"
      expose:
        - "5432"
      restart: always
      volumes:
        - postgres-volume:/var/lib/postgresql/data # persist the db
      networks:
        - mqtt_network

volumes:
    postgres-volume: